<a href="https://colab.research.google.com/github/jaganathan25/CNC_PYP1/blob/main/dataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.shape

(6, 4)

In [ ]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df=df.reset_index('temperature')
df

   temperature       day  windspeed  event
0           32  1/1/2017          6   Rain
1           35  1/2/2017          7  Sunny
2           28  1/3/2017          2   Snow
3           24  1/4/2017          7   Snow
4           32  1/5/2017          4   Rain
5           31  1/6/2017          2  Sunny

In [ ]:
df1=pd.read_csv("/content/weather_data (1).csv",parse_dates=['day'])
df1.set_index('day',inplace=True)
df1

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
new_df=df1.fillna(df['temperature'].median())
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         31.5        9.0   Sunny
2017-01-05         28.0       31.5    Snow
2017-01-06         31.5        7.0    31.5
2017-01-07         32.0       31.5    Rain
2017-01-08         31.5       31.5   Sunny
2017-01-09         31.5       31.5    31.5
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
new1_df=df1.fillna(method='bfill')
new1_df

/tmp/ipykernel_535/102400373.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new1_df=df1.fillna(method='bfill')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
new2_df=df1.interpolate()
new2_df

/tmp/ipykernel_535/3650064643.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new2_df=df1.interpolate()

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [ ]:
new3_df=df1.dropna(how="all")
new3_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

replace

In [ ]:
rdf=pd.read_csv("/content/weather_data (2).csv")
rdf

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [ ]:
import numpy as np

In [ ]:
rdf.replace({
    'temperature':-99999,
    'windspeed':-99999,
    'event':'0'
},np.nan)
rdf

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [ ]:
gdf=pd.read_csv("/content/weather_data (3).csv")
gdf

In [ ]:
gdf=pd.read_csv("/content/weather_by_cities.csv")
gdf

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [ ]:
g=gdf.groupby('city')
g

In [ ]:
for city,city_df in g:
  print(city)
  print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [ ]:
g.get_group('mumbai')

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [ ]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [ ]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

concat dataframe

In [ ]:
indian_weather=pd.DataFrame({
    'city':['chennai','mumbai','bombay'],
    'temp':[32,33,34],
    'hum':[80,60,70]
})
indian_weather

      city  temp  hum
0  chennai    32   80
1   mumbai    33   60
2   bombay    34   70

In [ ]:
us_weather=pd.DataFrame({
    'city':['newyork','chicago','orlando'],
    'temp':[21,14,35],
    'hum':[68,65,75]
})
us_weather

      city  temp  hum
0  newyork    21   68
1  chicago    14   65
2  orlando    35   75

In [ ]:
df=pd.concat([indian_weather,us_weather],keys=["india","us"])
df

            city  temp  hum
india 0  chennai    32   80
      1   mumbai    33   60
      2   bombay    34   70
us    0  newyork    21   68
      1  chicago    14   65
      2  orlando    35   75

In [ ]:
temp=pd.DataFrame({
    "city":["chennai","mumbai","bombay"],
    "temp":[32,34,33]
})
temp

      city  temp
0  chennai    32
1   mumbai    34
2   bombay    33

In [ ]:
hum=pd.DataFrame({
    "city":["chennai","mumbai","bombay"],
    "hum":[80,70,60]
})
hum

      city  hum
0  chennai   80
1   mumbai   70
2   bombay   60

In [ ]:
df=pd.concat([temp,hum],axis=1)
df

      city  temp     city  hum
0  chennai    32  chennai   80
1   mumbai    34   mumbai   70
2   bombay    33   bombay   60

In [ ]:
df=pd.merge(temp,hum,on="city",suffixes=('_left','_right'))
df

      city  temp  hum
0  chennai    32   80
1   mumbai    34   70
2   bombay    33   60